feat: better spotify parameters parsing
lukso-network/universalprofile.cloud pull request #485
Opened 2024-10-10 19:19 UTC by nastita

### Ticket ID
DEV-11779

### Description
Add support for spotify theme.
Use named capturing groups for better regex readability

2024-10-10 19:19 UTC, Hugoo commented
Task linked: [DEV-11779 Support Spotify `theme` param](https://app.clickup.com/t/2645698/DEV-11779)

2024-10-11 07:36 UTC, dzbo requested changes

2024-10-11 07:36 UTC, dzbo commented on domains/grid/utils/gridParser.ts
> +        src: `https://open.spotify.com/embed/${groups.type}/${groups.id}?utm_source=generator${theme}`,
Let's also include `theme` in properties

2024-10-14 12:06 UTC, dzbo approved these changes

2024-10-14 13:04 UTC, merged